### ISSUE TITLE
[Improvment] Download subtitles ?

### ISSUE THREAD

**Issue by leodomi** [box-archived/chrome-vlive-downloader#1]
Hi, thanks for this extension as it works really fine.

Is it possible to update it in order to download the subtitles too ?

Thanks for your response

**Comment by box-archived** [comment]
Now I'm preparing v2 release. I'll try to improve it in v2

**Comment by box-archived** [comment]
Included in rc version.
Now on testing

https://github.com/box-archived/chrome-vlive-downloader/releases/tag/v2.0.0-rc1

**Comment by leodomi** [comment]
Wow thank you for this update ☺

**Comment by box-archived** [comment]
Now released
check out chrome webstore!
https://chrome.google.com/webstore/detail/vlive-downloader/jhpjlmmgagjofmhmbpdhpjifdgghobkn
